"""
Export retrieved literature as PDF, BibTeX, RIS or plain text.

Two PDF layouts:

  "references"  A clean numbered Vancouver reference list — one or two pages,
                suitable for pasting into a manuscript's bibliography.

  "report"      A full research brief: query metadata, the grounded RAG answer
                with its citation markers, the reference list, and then each
                paper's abstract, MeSH headings and matched passages.

Built with ReportLab Platypus so long abstracts flow and paginate correctly.
"""

from __future__ import annotations

import io
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    ListFlowable,
    ListItem,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

from rag import citations

# --------------------------------------------------------------------------- #
INK = colors.HexColor("#16181d")
MUTED = colors.HexColor("#5b6270")
FAINT = colors.HexColor("#8a91a0")
ACCENT = colors.HexColor("#1d4ed8")
TEAL = colors.HexColor("#0d7a70")
RULE = colors.HexColor("#d8dce2")


def _styles() -> Dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    s: Dict[str, ParagraphStyle] = {}

    s["title"] = ParagraphStyle(
        "title", parent=base["Title"], fontName="Helvetica-Bold",
        fontSize=19, leading=23, textColor=INK, alignment=TA_LEFT,
        spaceAfter=2,
    )
    s["subtitle"] = ParagraphStyle(
        "subtitle", parent=base["Normal"], fontName="Helvetica",
        fontSize=9.5, leading=13, textColor=FAINT, spaceAfter=10,
    )
    s["h2"] = ParagraphStyle(
        "h2", parent=base["Heading2"], fontName="Helvetica-Bold",
        fontSize=12.5, leading=16, textColor=INK, spaceBefore=16, spaceAfter=6,
    )
    s["h3"] = ParagraphStyle(
        "h3", parent=base["Heading3"], fontName="Helvetica-Bold",
        fontSize=10.5, leading=14, textColor=INK, spaceBefore=10, spaceAfter=3,
    )
    s["body"] = ParagraphStyle(
        "body", parent=base["Normal"], fontName="Helvetica",
        fontSize=9.8, leading=14.5, textColor=INK, alignment=TA_JUSTIFY,
        spaceAfter=6,
    )
    s["meta"] = ParagraphStyle(
        "meta", parent=base["Normal"], fontName="Helvetica",
        fontSize=8.6, leading=12, textColor=MUTED, spaceAfter=3,
    )
    s["label"] = ParagraphStyle(
        "label", parent=base["Normal"], fontName="Helvetica-Bold",
        fontSize=7.6, leading=10, textColor=TEAL, spaceAfter=2,
    )
    s["ref"] = ParagraphStyle(
        "ref", parent=base["Normal"], fontName="Helvetica",
        fontSize=9.2, leading=13.5, textColor=INK, spaceAfter=7,
        leftIndent=14, firstLineIndent=-14,
    )
    s["quote"] = ParagraphStyle(
        "quote", parent=base["Normal"], fontName="Helvetica-Oblique",
        fontSize=9, leading=13.5, textColor=MUTED,
        leftIndent=10, borderPadding=0, spaceAfter=5,
    )
    s["answer"] = ParagraphStyle(
        "answer", parent=base["Normal"], fontName="Helvetica",
        fontSize=10.2, leading=16, textColor=INK, alignment=TA_JUSTIFY,
        spaceAfter=8,
    )
    return s


# --------------------------------------------------------------------------- #
def _esc(text: Any) -> str:
    """Escape for ReportLab's mini-HTML paragraph markup."""
    return (
        str(text if text is not None else "")
        .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    )


def _cite_markers(text: str) -> str:
    """Render [1] citation markers as small superscripts."""
    return re.sub(r"\[(\d+)\]", r'<super><font color="#1d4ed8">[\1]</font></super>', text)


def _footer(canvas, doc):  # noqa: ANN001
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(FAINT)
    canvas.drawString(
        20 * mm, 12 * mm,
        "Generated by PubMed Semantic Search (RAG) · data from NCBI PubMed",
    )
    canvas.drawRightString(A4[0] - 20 * mm, 12 * mm, f"Page {doc.page}")
    canvas.setStrokeColor(RULE)
    canvas.setLineWidth(0.4)
    canvas.line(20 * mm, 16 * mm, A4[0] - 20 * mm, 16 * mm)
    canvas.restoreState()


# --------------------------------------------------------------------------- #
def build_pdf(
    articles: List[Dict[str, Any]],
    mode: str = "references",
    query: str = "",
    answer: Optional[Dict[str, Any]] = None,
    stages: Optional[Dict[str, Any]] = None,
    title: str = "",
) -> bytes:
    """Render the export to a PDF and return the raw bytes."""
    mode = (mode or "references").lower()
    buf = io.BytesIO()
    s = _styles()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=18 * mm, bottomMargin=22 * mm,
        title=title or (f"PubMed references — {query}" if query else "PubMed references"),
        author="PubMed Semantic Search (RAG)",
        subject=query or "PubMed literature export",
    )

    story: List[Any] = []
    stamp = datetime.now().strftime("%d %b %Y, %H:%M")

    # ---------------- header ----------------
    heading = title or (
        "Literature Report" if mode == "report" else "Reference List"
    )
    story.append(Paragraph(_esc(heading), s["title"]))
    sub = [f"{len(articles)} record(s)", stamp]
    if query:
        sub.insert(0, f"Query: “{_esc(query)}”")
    story.append(Paragraph(" &nbsp;·&nbsp; ".join(sub), s["subtitle"]))
    story.append(HRFlowable(width="100%", thickness=0.7, color=RULE,
                            spaceBefore=2, spaceAfter=4))

    # ---------------- report-only preamble ----------------
    if mode == "report":
        if stages:
            rows = []
            if stages.get("total_matches"):
                rows.append(f"PubMed matches: {stages['total_matches']:,}")
            if stages.get("pubmed_query"):
                rows.append(f"Search sent to ESearch: {_esc(stages['pubmed_query'])}")
            if stages.get("mesh_terms"):
                rows.append("MeSH terms matched: " +
                            _esc("; ".join(stages["mesh_terms"])))
            emb = stages.get("embedding") or {}
            if emb.get("model"):
                rows.append(
                    f"Embedding model: {_esc(emb['model'])} "
                    f"({emb.get('dim', '?')}-d, {_esc(emb.get('kind', ''))})"
                )
            if rows:
                story.append(Paragraph("Search parameters", s["h2"]))
                for row in rows:
                    story.append(Paragraph(row, s["meta"]))

        if answer and (answer.get("answer") or "").strip():
            story.append(Paragraph("Grounded answer", s["h2"]))
            for para in str(answer["answer"]).split("\n"):
                para = para.strip()
                if para:
                    story.append(Paragraph(_cite_markers(_esc(para)), s["answer"]))
            story.append(Paragraph(
                "Every sentence above is extracted verbatim from the numbered "
                "sources below; bracketed markers map to the reference list.",
                s["meta"],
            ))

    # ---------------- reference list ----------------
    story.append(Paragraph("References", s["h2"]))
    if not articles:
        story.append(Paragraph("No records selected.", s["body"]))
    else:
        items = []
        for a in articles:
            text = _esc(citations.vancouver(a))
            url = a.get("url")
            if url:
                text = text.replace(
                    f"PMID: {a.get('pmid')}.",
                    f'<link href="{_esc(url)}" color="#1d4ed8">'
                    f"PMID: {_esc(a.get('pmid'))}</link>.",
                )
            items.append(ListItem(Paragraph(text, s["ref"]), leftIndent=16))
        story.append(ListFlowable(items, bulletType="1", bulletFontSize=9.2,
                                  leftIndent=16, bulletDedent=16))

    # ---------------- per-paper detail ----------------
    if mode == "report" and articles:
        story.append(PageBreak())
        story.append(Paragraph("Abstracts", s["h2"]))

        for i, a in enumerate(articles, start=1):
            block: List[Any] = [
                Paragraph(f"{i}. {_esc(a.get('title') or '[No title]')}", s["h3"]),
                Paragraph(
                    " · ".join(
                        _esc(x) for x in [
                            citations.author_string(a.get("authors") or [], 3),
                            a.get("journal") or "",
                            a.get("pub_date") or a.get("year") or "",
                            f"PMID {a.get('pmid')}",
                        ] if x
                    ),
                    s["meta"],
                ),
            ]

            abstract = (a.get("abstract") or "").strip()
            block.append(Paragraph(
                _esc(abstract) if abstract
                else "<i>No abstract available for this record.</i>",
                s["body"],
            ))

            # Prefer a real abstract passage — the title/MeSH chunk just
            # repeats the heading printed two lines above.
            passages = [
                p for p in (a.get("matched_passages") or [])
                if (p.get("section") or "").lower() != "title"
            ]
            if passages:
                snippet = re.sub(r"\s*MeSH:[^.]*", "", str(passages[0].get("text", "")))
                snippet = re.sub(r"^.*?\s—\s", "", snippet).strip()
                if snippet and snippet.lower() not in (a.get("title") or "").lower():
                    label = passages[0].get("section") or ""
                    block.append(Paragraph(
                        f"MATCHED PASSAGE{' · ' + label.upper() if label else ''}",
                        s["label"],
                    ))
                    block.append(Paragraph(f"“{_esc(snippet[:600])}”", s["quote"]))

            mesh = a.get("mesh_terms") or []
            if mesh:
                block.append(Paragraph("MESH HEADINGS", s["label"]))
                block.append(Paragraph(_esc("; ".join(mesh)), s["meta"]))

            block.append(Spacer(1, 4))
            block.append(HRFlowable(width="100%", thickness=0.4, color=RULE,
                                    spaceBefore=2, spaceAfter=8))
            # Keep a paper's heading with at least its metadata line.
            story.append(KeepTogether(block[:3]))
            story.extend(block[3:])

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


# --------------------------------------------------------------------------- #
FORMATS = {
    "pdf": ("application/pdf", "pdf"),
    "bib": ("application/x-bibtex", "bib"),
    "ris": ("application/x-research-info-systems", "ris"),
    "txt": ("text/plain; charset=utf-8", "txt"),
}


def build(
    fmt: str,
    articles: List[Dict[str, Any]],
    mode: str = "references",
    query: str = "",
    answer: Optional[Dict[str, Any]] = None,
    stages: Optional[Dict[str, Any]] = None,
) -> bytes:
    fmt = (fmt or "pdf").lower()
    if fmt == "pdf":
        return build_pdf(articles, mode=mode, query=query, answer=answer,
                         stages=stages)
    if fmt == "bib":
        return citations.bibtex(articles).encode("utf-8")
    if fmt == "ris":
        return citations.ris(articles).encode("utf-8")
    if fmt == "txt":
        return citations.plain_text(articles).encode("utf-8")
    raise ValueError(f"Unsupported export format: {fmt}")


def filename(fmt: str, query: str = "", mode: str = "references") -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "-", (query or "pubmed")).strip("-").lower()
    slug = (slug[:48] or "pubmed").rstrip("-")
    stamp = datetime.now().strftime("%Y%m%d-%H%M")
    kind = "report" if mode == "report" and fmt == "pdf" else "refs"
    return f"{slug}-{kind}-{stamp}.{FORMATS.get(fmt, ('', fmt))[1]}"
